// Vercel cron: draft the morning briefing before Mason is awake.
//
// Scheduled from vercel.json at "0 11 * * 1-5". Vercel cron is UTC-ONLY and Hobby fires anywhere
// inside the scheduled hour, so the job is really choosing a one-hour window that has to stay
// sensible across DST. 11:00 UTC is 06:00-06:59 Central in summer and 05:00-05:59 in winter, and
// both windows sit entirely before the 07:30 CT economic releases and the 08:30 CT open — so the
// briefing has the same character every day. 12:00 UTC would straddle the data drop all summer.
// Weekdays only: a Saturday briefing has no session to report and would still cost ~$0.30.
//
// This is a SCHEDULER, not a second implementation. It calls the same /api/brief endpoint the
// browser does, so there is one code path for drafting a briefing and one place for it to go wrong.
// Each inner call is its own invocation with its own duration budget, which is also why the draft
// and the so-what are two requests rather than one long one.
//
// The fact-check is deliberately NOT run here. It costs about what the draft does and grades a
// briefing nobody has read yet; it stays a button.
//
// Env: CRON_SECRET (Vercel sends it as `Authorization: Bearer …`), plus the SYNC_SECRET and
// ANTHROPIC_KEY that /api/brief already needs.
import { timingSafeEqual } from "node:crypto";

export const config = { maxDuration: 300 };

function authed(req) {
  const want = process.env.CRON_SECRET || "";
  const got = String(req.headers.authorization || "");
  const expect = `Bearer ${want}`;
  if (!want || !got) return false;
  const a = Buffer.from(expect), b = Buffer.from(got);
  if (a.length !== b.length) return false; // timingSafeEqual throws on length mismatch
  return timingSafeEqual(a, b);
}

// Prefer the stable production domain over VERCEL_URL, which is the per-deployment hostname: a
// cron firing against a deployment-specific URL still works, but the logs read as though a
// preview generated production's briefing.
function baseUrl() {
  const host = process.env.VERCEL_PROJECT_PRODUCTION_URL || process.env.VERCEL_URL;
  return host ? `https://${host}` : null;
}

export default async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store");
  if (!authed(req)) return res.status(401).json({ error: "unauthorized" });
  if (!process.env.SYNC_SECRET) return res.status(503).json({ error: "SYNC_SECRET is not configured" });
  const base = baseUrl();
  if (!base) return res.status(503).json({ error: "no deployment URL to call" });

  const run = async step => {
    const r = await fetch(`${base}/api/brief`, {
      method: "POST",
      headers: { "content-type": "application/json", "x-mjb-sync": process.env.SYNC_SECRET },
      body: JSON.stringify({ type: "morning", step }),
    });
    let d = null; try { d = await r.json(); } catch {}
    return { ok: r.ok, status: r.status, body: d };
  };

  // No `force`. A cron that redrafted would double-bill the morning whenever Vercel delivers the
  // same scheduled run twice — which their docs say happens — and would also throw away a briefing
  // Mason had already generated by hand before the job fired.
  const draft = await run("brief");
  if (!draft.ok) {
    console.error(`[cron-brief] draft failed ${draft.status}:`, draft.body && draft.body.error);
    return res.status(502).json({ step: "brief", status: draft.status, error: draft.body && draft.body.error });
  }
  const reused = !!(draft.body && draft.body.reused);
  console.log(`[cron-brief] draft ok — ${reused ? "reused an existing briefing" : `${(draft.body && draft.body.searches) || 0} searches`}`);

  // Only worth running if the record doesn't already carry it.
  let soWhat = "skipped";
  if (!(draft.body && draft.body.soWhat)) {
    const sw = await run("sowhat");
    soWhat = sw.ok ? "ok" : `failed ${sw.status}`;
    if (!sw.ok) console.error("[cron-brief] sowhat failed:", sw.body && sw.body.error);
  }
  // A failed so-what is not a failed briefing — the text is already stored and readable.
  return res.status(200).json({ ok: true, date: draft.body && draft.body.date, reused, soWhat });
}
